### ISSUE TITLE
Using the ES6

### ISSUE THREAD

**Issue by ali-master** [mahmoud-eskandari/IPTT#3]
Hi there,

As you know, after v49, the Chrome browser has been added and supported the ES6 classes feature and now, you can use this features in your extension's code. So Do you have any plan to update?

**Comment by mahmoud-eskandari** [comment]
No , I'm sorry :| I haven't any plan or idea for it , I don`t have strong skills in ES6  :)
 because I'm a back-end developer!
I made this project in less than 1 hour , Just for fun!

**Comment by ali-master** [comment]
Great job man.

I'd appreciate your project.
